/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-06-22 04:04:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>심리테스트</title>\r\n");
      out.write("<style>\r\n");
      out.write("html,body{\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            min-width: 100vw;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("  \t \tbackground-image: url(\"home/home.jpg\") ;\r\n");
      out.write("   \t\tbackground-color: #cccccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("        .parent{\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .parent>.row{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .col{\r\n");
      out.write("            width: 200%;\r\n");
      out.write("        }\r\n");
      out.write("        .col img{\r\n");
      out.write("            height:200px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: transform 1s;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("        .col label{\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .imgbgchk:checked + label>.tick_container{\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("/*         aNIMATION */\r\n");
      out.write("        .imgbgchk:checked + label>img{\r\n");
      out.write("            opacity: 0.8;\r\n");
      out.write("        }\r\n");
      out.write("        .tick_container {\r\n");
      out.write("            transition: .5s ease;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            -ms-transform: translate(-50%, -50%);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .tick {\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 6px 12px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("        } \r\n");
      out.write("            .btn {\r\n");
      out.write("  -webkit-border-radius: 28;\r\n");
      out.write("  -moz-border-radius: 28;\r\n");
      out.write("  border-radius: 28px;\r\n");
      out.write("  font-family: Arial;\r\n");
      out.write("  color: #000000;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  background: #fffc2e;\r\n");
      out.write("  padding: 10px 20px 10px 20px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  margin:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("  background: #ffdd00;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" integrity=\"sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"homeResult.jsp\">\r\n");
      out.write("    <div class=\"container parent\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class='col text-center'>\r\n");
      out.write("        <input type=\"radio\" name=\"home\" id=\"img1\" class=\"d-none imgbgchk\" value=\"1\">\r\n");
      out.write("          <label for=\"img1\">\r\n");
      out.write("            <img src=\"home/1.png\" alt=\"문이 두 개인 집\">\r\n");
      out.write("            <div class=\"tick_container\">\r\n");
      out.write("              <div class=\"tick\"><i class=\"fa fa-check\"></i></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class='col text-center'>\r\n");
      out.write("        <input type=\"radio\" name=\"home\" id=\"img2\" class=\"d-none imgbgchk\" value=\"2\" checked>\r\n");
      out.write("          <label for=\"img2\">\r\n");
      out.write("            <img src=\"home/2.png\" alt=\"창문이 많은 집\">\r\n");
      out.write("            <div class=\"tick_container\">\r\n");
      out.write("              <div class=\"tick\"><i class=\"fa fa-check\"></i></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class='col text-center'>\r\n");
      out.write("        <input type=\"radio\" name=\"home\" id=\"img3\" class=\"d-none imgbgchk\" value=\"3\">\r\n");
      out.write("          <label for=\"img3\">\r\n");
      out.write("            <img src=\"home/3.png\" alt=\"지붕이 큰 집\">\r\n");
      out.write("            <div class=\"tick_container\">\r\n");
      out.write("              <div class=\"tick\"><i class=\"fa fa-check\"></i></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class='col text-center'>\r\n");
      out.write("        <input type=\"radio\" name=\"home\" id=\"img4\" class=\"d-none imgbgchk\" value=\"4\">\r\n");
      out.write("            <label for=\"img4\">\r\n");
      out.write("              <img src=\"home/4.png\" alt=\"굴뚝이 있는 집\">\r\n");
      out.write("              <div class=\"tick_container\">\r\n");
      out.write("                <div class=\"tick\"><i class=\"fa fa-check\"></i></div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"submit\" class=\"btn\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
