/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-06-21 13:34:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"https://www.emirim.REYOLA.com\" />\r\n");
      out.write("    <meta property=\"title\" content=\"누구나 즐길 수 있는 YOLO, REYOLA\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script> \r\n");
      out.write("    <script src=\"http://malsup.github.com/jquery.cycle2.js\"></script>\r\n");
      out.write("    <title>누구나 즐길 수 있는 YOLO, REYOLA</title>\r\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Open+Luckiest Guy,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Luckiest Guy,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href=\"vendor/magnific-popup/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/index_css.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body id=\"page-top\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\" id=\"mainNav\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">REYOLA</a>\r\n");
      out.write("        <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"> <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link js-scroll-trigger\" href=\"#about\">About YOLO</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link js-scroll-trigger\" href=\"#travel\">Travel</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link js-scroll-trigger\" href=\"#share\">Share</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link js-scroll-trigger\" href=\"#contact\">Made by</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <header class=\"masthead text-center text-white d-flex\">\r\n");
      out.write("      <div class=\"container my-auto\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-10 mx-auto\">\r\n");
      out.write("            <h1 class=\"text-uppercase\">\r\n");
      out.write("              <br><br><br>\r\n");
      out.write("              <span style= \"background-color:#212121\"><strong>누구나 즐길 수 있는<br>YOLO LIFE</strong></span>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <hr class=\"light\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("            <span style=\"background-color:#212121\">지금 즐기러 가실래요?</span><br><br><br><br>\r\n");
      out.write("            <a class=\"btn btn-primary btn-xl js-scroll-trigger sr-button\" href=\"#about\">FIND OUT MORE</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"bg-primary\" id=\"about\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-8 mx-auto text-center\">\r\n");
      out.write("            <h2 class=\"section-heading text-black\"><span style=\"color:white\"><b>[YOLO]<div>You Only Live Once</b></h2></span>\r\n");
      out.write("            <hr class=\"light my-4\">\r\n");
      out.write("            <p class=\"mb-4 text-black\">인생은 단 한번 뿐! 후회없이 즐기자! </p>\r\n");
      out.write("            <div> <br> <br>\r\n");
      out.write("            <a class=\"btn btn-light btn-xl js-scroll-trigger sr-button\" href=\"checkList.jsp\">YOLO지수 검사하기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"travel\">\r\n");
      out.write("      <div class=\"container\" >\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-12 text-center\">\r\n");
      out.write("           <br><br><br><br><br> <h2 class=\"section-heading\">Travel</h2>\r\n");
      out.write("            <hr class=\"my-4\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("            <div class=\"service-box mt-5 mx-auto\">\r\n");
      out.write("            <i class=\"fa fa-4x fa-heart text-primary mb-3 sr-icons\"></i>\r\n");
      out.write("              <h5 class=\"mb-3\">HAPPINESS</h5>\r\n");
      out.write("              <p class=\"text-muted mb-0\">행복</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("            <div class=\"service-box mt-5 mx-auto\">\r\n");
      out.write("              <i class=\"fa fa-4x fa-plane text-primary mb-3 sr-icons\"></i>\r\n");
      out.write("              <h5 class=\"mb-3\">FRESH</h5>\r\n");
      out.write("              <p class=\"text-muted mb-0\">새로움</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("            <div class=\"service-box mt-5 mx-auto\">\r\n");
      out.write("              <i class=\"fa fa-4x fa-comments text-primary mb-3 sr-icons\"></i>\r\n");
      out.write("              <h5 class=\"mb-3\">COMMUNICATE</h5>\r\n");
      out.write("              <p class=\"text-muted mb-0\">소통</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("            <div class=\"service-box mt-5 mx-auto\">\r\n");
      out.write("              <i class=\"fa fa-4x fa-music text-primary mb-3 sr-icons\"></i>\r\n");
      out.write("              <h5 class=\"mb-3\">JOY</h5>\r\n");
      out.write("              <p class=\"text-muted mb-0\">즐거움</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("          <br>\r\n");
      out.write("          <a class=\"btn btn-primary2 btn-xl js-scroll-trigger sr-button\"  href=\"ourYOLO.jsp\">WHERE TO GO</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"share\" class=\"cycle-slideshow\" data-cycle-fx=\"scrollHorz\"\r\n");
      out.write("    data-cycle-pause-on-hover=\"true\"\r\n");
      out.write("    data-cycle-speed=\"1000\">\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"bg-dark text-black\">\r\n");
      out.write("      <div class=\"container text-center\">\r\n");
      out.write("        <h2 class=\"mb-4\">Share</h2>\r\n");
      out.write("        <hr class=\"light my-4\">\r\n");
      out.write("        <p class=\"mb-4 text-black\">자신만의 YOLO한 장소를<br>공유해보세요!</p>\r\n");
      out.write("        <a class=\"btn btn-light btn-xl js-scroll-trigger sr-button\" href=\"Share_Board.jsp\">Share Now!</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"contact\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-8 mx-auto text-center\">\r\n");
      out.write("            <h2 class=\"section-heading\">Made by</h2>\r\n");
      out.write("            <hr class=\"my-4\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4 ml-auto text-center\">\r\n");
      out.write("          <img src=\"img/REYOLABLACK.png\" height=\"57px\">\r\n");
      out.write("            <i class=\"fa-3x mb-3 sr-contact\"></i>\r\n");
      out.write("            <p></p><p>차수연<br>김서연<br>이예본 </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 ml-auto text-center\">\r\n");
      out.write("            <i class=\"fa fa-phone fa-3x mb-3 sr-contact\"></i>\r\n");
      out.write("            <p>010-3374-6079<br>010-7762-1299<br>010-5771-8220</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 mr-auto text-center\">\r\n");
      out.write("            <i class=\"fa fa-envelope-o fa-3x mb-3 sr-contact\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              \tchasu1228@naver.com<br>seoyeonkim@gmail.com<br>proglobe22@gmail.com\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</font>\r\n");
      out.write("    <!-- Bootstrap core JavaScript -->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin JavaScript -->\r\n");
      out.write("    <script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/scrollreveal/scrollreveal.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for this template -->\r\n");
      out.write("    <script src=\"js/creative.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
